### ISSUE TITLE
undefined function socket_create()

### ISSUE THREAD

**Issue by rdlmda** [9gag-open-source/fpm-health-check#1]
I've built the docker image from https://hub.docker.com/r/9gag/fpm-health-check

```
Fatal error: Uncaught Error: Call to undefined function EBernhardson\FastCGI\socket_create() in phar:///fpm-health-check.phar/vendor/ebernhardson/fastcgi/lib/EBernhardson/FastCGI/Client.php:226
Stack trace:
#0 phar:///fpm-health-check.phar/vendor/ebernhardson/fastcgi/lib/EBernhardson/FastCGI/Client.php(465): EBernhardson\FastCGI\Client->connect()
#1 phar:///fpm-health-check.phar/vendor/ebernhardson/fastcgi/lib/EBernhardson/FastCGI/Client.php(445): EBernhardson\FastCGI\Client->asyncRequest(Array, '')
#2 phar:///fpm-health-check.phar/FpmCheck/Cli.php(41): EBernhardson\FastCGI\Client->request(Array, '')
#3 phar:///fpm-health-check.phar/vendor/symfony/console/Command/Command.php(242): class@anonymous->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///fpm-health-check.phar/vendor/symfony/console/Application.php(842): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output in phar:///fpm-health-check.phar/vendor/ebernhardson/fastcgi/lib/EBernhardson/FastCGI/Client.php on line 226
```

**Comment by derek9gag** [comment]
Thank you for reporting. This should be fixed in master.
